//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TridionCommunity.Extensions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TridionCommunity.Extensions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot enable an uninstalled extension..
        /// </summary>
        internal static string ErrCannotEnableUninstalledExtension {
            get {
                return ResourceManager.GetString("ErrCannotEnableUninstalledExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has not yet been loaded..
        /// </summary>
        internal static string ErrConfigurationNotLoaded {
            get {
                return ResourceManager.GetString("ErrConfigurationNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist..
        /// </summary>
        internal static string ErrDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("ErrDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string ErrFileDoesNotExist {
            get {
                return ResourceManager.GetString("ErrFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension &apos;{0}&apos; was not found..
        /// </summary>
        internal static string ErrInvalidExtensionInfo {
            get {
                return ResourceManager.GetString("ErrInvalidExtensionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.xml is invalid..
        /// </summary>
        internal static string ErrInvalidExtensionXml {
            get {
                return ResourceManager.GetString("ErrInvalidExtensionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SDL manifest file is invalid or does not contain the expected elements..
        /// </summary>
        internal static string ErrInvalidSdlManifestFile {
            get {
                return ResourceManager.GetString("ErrInvalidSdlManifestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required section in the System.config file: {0}.
        /// </summary>
        internal static string ErrMissingSectionInSystemConfig {
            get {
                return ResourceManager.GetString("ErrMissingSectionInSystemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required property not set: {0}.
        /// </summary>
        internal static string ErrRequiredPropertyNotSet {
            get {
                return ResourceManager.GetString("ErrRequiredPropertyNotSet", resourceCulture);
            }
        }
    }
}
